# Generated by Django 4.0 on 2022-11-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='primaryCategory',
        ),
    ]
